account:
  user: '學號'
  passwd: '密碼'

notifications:
  tg:
    enable: False
    key: 'botxxx:xxx'
    chat: '123456789'

  

config:
  enable_log: true
  Senkaku: 1
  retries: 10
  user-agent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/136.0.0.0 Safari/537.36 Edge/136.0.0.0'